# Generated by Django 2.2 on 2019-05-11 08:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Course')),
                ('selection_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Student')),
            ],
        ),
    ]
