# Generated by Django 2.2 on 2019-04-17 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banji_name', models.TextField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.TextField(default='', unique=True)),
                ('classroom_capacity', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(default='')),
                ('course_credit', models.IntegerField(default=1)),
                ('course_type', models.IntegerField(default=0)),
                ('course_year', models.IntegerField(default=2018)),
                ('course_semester', models.IntegerField(default=2)),
                ('course_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.TextField(default='', unique=True)),
                ('student_name', models.TextField(default='')),
                ('student_email', models.EmailField(default='test@test.com', max_length=254)),
                ('student_start_year', models.IntegerField(default=2016)),
                ('student_end_year', models.IntegerField(default=2020)),
                ('student_banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Banji')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.TextField(default='')),
                ('teacher_number', models.TextField(default='', unique=True)),
                ('teacher_email', models.EmailField(default='test@test.com', max_length=254)),
                ('teacher_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Department')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='', unique=True)),
                ('user_password', models.TextField(default='')),
                ('user_token', models.TextField(default='')),
                ('user_type', models.IntegerField(default=2)),
                ('user_permission', models.TextField(default='{}')),
                ('user_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Student')),
                ('user_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.TextField(default='', unique=True)),
                ('major_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.TextField(default='')),
                ('exam_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Course')),
            ],
        ),
        migrations.CreateModel(
            name='DateAndClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True)),
                ('semester', models.IntegerField(blank=True)),
                ('start_week', models.IntegerField(blank=True)),
                ('end_week', models.IntegerField(blank=True)),
                ('day_of_week', models.IntegerField(blank=True)),
                ('start', models.IntegerField(blank=True)),
                ('end', models.IntegerField(blank=True)),
                ('start_date_time', models.DateTimeField(blank=True)),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Department'),
        ),
        migrations.AddField(
            model_name='banji',
            name='banji_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Major'),
        ),
    ]
