# Generated by Django 2.2 on 2019-04-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_delete_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_classroom',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='course_capacity',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entity.Department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DateAndClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True)),
                ('semester', models.IntegerField(blank=True)),
                ('start_week', models.IntegerField(blank=True)),
                ('end_week', models.IntegerField(blank=True)),
                ('day_of_week', models.IntegerField(blank=True)),
                ('start', models.IntegerField(blank=True)),
                ('end', models.IntegerField(blank=True)),
                ('start_date_time', models.DateTimeField(blank=True)),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Exam')),
            ],
        ),
    ]
