# Generated by Django 2.2 on 2019-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.TextField(default='', unique=True)),
                ('notice_author', models.IntegerField(default='')),
                ('notice_date', models.DateTimeField(default='')),
                ('notice_receiver', models.IntegerField()),
                ('notice_content', models.TextField(default='')),
            ],
        ),
    ]
