# Generated by Django 2.2 on 2019-04-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_tester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
