# Generated by Django 2.2 on 2019-04-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoremng', '0002_auto_20190414_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
    ]
