# Generated by Django 2.2 on 2019-04-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoremng', '0003_auto_20190414_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='course_id',
            new_name='course',
        ),
    ]
