# Generated by Django 2.2 on 2019-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremng', '0004_auto_20190414_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
