# Generated by Django 2.2 on 2019-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremng', '0006_selectcourse_teacherschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='semester',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
