# Generated by Django 2.2 on 2019-04-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_delete_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Course')),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Student')),
            ],
        ),
    ]
